#!/bin/bash

# Create a dummy bval and bvec files with zeros
# The number of zeros is determined by the number of volumes in input file (4D data required)
# Script is useful for DWI acquistions containing only b0 volumes because no .bval and .bvec files are created for these acquisitons
# by dcm2niix script

# For example, if the input file has 8 b0 volumes, output files look like:
# bval:
#       0 0 0 0 0 0 0 0
# bvec:
#       0 0 0 0 0 0 0 0
#       0 0 0 0 0 0 0 0
#       0 0 0 0 0 0 0 0

# Jan Valosek, fMRI laboratory Olomouc, Czechia, 2022

if [[ $# -eq 0 ]] || [[ $1 =~ "-h" ]];then
    echo "Creaty dummy bval and bvec files with zeros."
    echo "The number of zeros is determined by the number of volumes in input file (4D data required)."
    echo -e "USAGE:\n\t${0##*/} <input 4D diffusion image>"
    echo -e "EXAMPLE:\n\t${0##*/} dmri_PA_only_b0.nii.gz"
    exit
fi

input_file=$1

# Get number of volumes (4th dimension)
num_of_volumes=$(fslval ${input_file} dim4)

output_bval_filename=$(echo ${input_file%%.*})     # strip out suffix
zeros=""

# Loop across number of b0 volumes in the input data
for i in $(seq ${num_of_volumes});do
    zeros="${zeros}0 "
done

# Backup .bval if already exists
if [[ -f ${output_bval_filename}.bval ]]; then
    mv ${output_bval_filename}.bval ${output_bval_filename}.bval.backup
fi

# Backup .bvec if already exists
if [[ -f ${output_bval_filename}.bvec ]]; then
    mv ${output_bval_filename}.bvec ${output_bval_filename}.bvec.backup
fi

# Print zeros into txt bval file (one line file)
echo ${zeros} >> ${output_bval_filename}.bval

# Print zeros into txt bvec file (three line file)
echo ${zeros} >> ${output_bval_filename}.bvec; echo ${zeros} >> ${output_bval_filename}.bvec; echo ${zeros} >> ${output_bval_filename}.bvec

echo -e "Created ${output_bval_filename}.bval and ${output_bval_filename}.bvec"
echo -e "${0##*/} finished\n"
