#!/bin/bash

# Function for checking existency of directories or files
# USAGE:
#   check_input.sh <argument> "DIR_NAME(s) or FILE_NAME(s)"
# ARGUMENTS:
#   d - check if directory exists
#   dc - check if directory exists, if not create it
#   f - check if file exists
#   e - check if binary exist and is executable

# Jan Valosek, fMRI laboratory, Olomouc, 2019-2020. Inspired by Pavel Hok
# VER=27-12-2019

flag="$1"
shift

if [[ $flag =~ "h" ]] || [[ $flag == "" ]]; then
  echo -e "Help for function for checking existency of directories or files.\nUSAGE:\n\tcheck_input <argument> DIR_NAME(s) or FILE_NAME(s) or SCRIPT_NAME(s)"
  exit
fi

# Function telling to parent process that something happened (e.g. file does not exist)
# Function finds parent process ID (ppid) and set user defined signal (SIGUSR1)
# Inspiration:
#     https://stackoverflow.com/questions/16215196/bash-exit-parent-script-from-child-script
trap_exit()
{
    OS_name=$(uname -a | awk '{print $1}')  # get OS name (Darwin or Linux)

    if [[ $OS_name == "Linux" ]]; then
        kill -SIGUSR1 `ps --pid $$ -o ppid=`;exit   # Find parent process ID (ppid) and set user defined signal (SIGUSR1)
    elif [[ $OS_name == "Darwin" ]]; then
        kill -SIGUSR1 `ps $$ -o ppid=`;exit         # Find parent process ID (ppid) and set user defined signal (SIGUSR1)
    fi
}


while [[ "$1" != "" ]]; do
  case $flag in
    # Check if directory exists
    d)
        if [[ ! -d "$1" ]]; then
          echo "Directory $1 does not exist."
          trap_exit
        fi
        ;;
    # Check if directory exists, if not create it
    dc)
        if [[ ! -d "$1" ]]; then
          echo "Creating $1 directory."
          mkdir $1
          if [[ ! -d "$1" ]]; then
            echo "Directory $1 could not be created."
            trap_exit
          fi
        fi
        ;;
    # Check if file exists
    f)
        if [[ ! -f "$1" ]]; then
          echo "File $1 does not exist."
          trap_exit
        fi
        ;;
    # Check if script/function exists and is executable, if not, set permissions (to 770)
    e)
        if [[ ! -x "$1" ]]; then
            if [[ ! -f "$1" ]]; then
                echo "Function/Script $1 does not exist"
                trap_exit
            else
                chmod 770 $1
                if [[ ! -x "$1" ]]; then
                    echo "Fuction/Script $1 is not executable and permissions can not be set."
                    trap_exit
                fi
            fi
        fi
        ;;
  esac
  shift
done
