#!/bin/bash

# If two same DWI acqusition only with oposite PE are acquired, this script merges
# bval/bvec files into one. Outputs can be then used for eddy function.

# Jan Valosek, fMRI laboratory Olomouc, Czechia, 2021

if [[ $# -eq 0 ]] || [[ $1 =~ "-h" ]];then
    echo "Merge two bval/bvec files into one."
    echo -e "USAGE:\n\t${0##*/} <first bval/bvec file> <second bval/bvec file>\nExample:\n\t${0##*/} dti_AP.bval dti_PA.bval\n\t${0##*/} dti_AP.bvec dti_PA.bvec"
    exit
fi

# Get suffix (bval or bvec)
suffix=${1#*.}
output_file_name="dti_merged.${suffix}"

paste -d ' ' ${1} ${2} > ${output_file_name}

echo -e "Created ${output_file_name}:\n$(cat ${output_file_name})"
