#!/bin/bash

# Create a text file for FSL's topup function
# The text file will have 4 columns and number of rows corresponding to total
# number of b0 volumes
# See for details:
#     https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/TopupUsersGuide#A--datain

# Jan Valosek, fMRI laboratory Olomouc, Czechia, 2021

if [[ $# -eq 0 ]] || [[ $1 =~ "-h" ]];then
  echo "Create a text file for FSL's topup function from input b0 files."
  echo "The text file will have 4 columns and number of rows corresponding to total number of b0 volumes."
  echo -e "\nNOTE:\n\t- script currently supports only AP-PA or PA-AP phase encoding\n\t- default readout time is 0.1, if not passed othwerwise!"
  echo "Why 0.1? See - https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;d552bccb.1312"
  echo -e "For details about topup file see - https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/TopupUsersGuide#A--datain"
  echo -e "\nUSAGE:\n\t${0##*/} <b0_AP> <b0_PA> <phase_endocing> <readout_time>\nExample:\n\t${0##*/} dmri_AP_b0.nii.gz dmri_PA_b0.nii.gz AP-PA 0.076"
  echo -e "\nTIP: you can get <readout_time> by get_readout function, like this:"
  echo -e "\t${0##*/} dmri_AP_b0.nii.gz dmri_PA_b0.nii.gz AP-PA \$(get_readout dmri_AP.json)"
  exit
fi

# Uncomment for debug
#set -x

# Immediately exit if error
set -e -o pipefail

# Global variables
output_file_name="topup.txt"    # filename for output text file
readout=0.1                     # default readout time, if not passed othwerwise - see https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;d552bccb.1312
first_input_file=${1/.nii*/}      # Strip out .nii or .nii.gz sufix if passed
second_input_file=${2/.nii*/}      # Strip out .nii or .nii.gz sufix if passed
first_size="$(fslval ${first_input_file}.nii.gz dim4)"   # number of volumes in the first image
second_size="$(fslval ${second_input_file}.nii.gz dim4)"   # number of volumes in the second image

# Init

# Set AP-PA or PA-AP phase encoding
# Note:
#   A-P corresponds with 0 -1 0
#   P-A corresponds with 0 1 0
# For details see https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/Faq#How_do_I_know_what_to_put_into_my_--acqp_file.3F
# First file is AP -> set -1
if [[ ${3} == "AP-PA" ]]; then
    first_sign="-"
    second_sign=""
# First file is PA -> set 1
elif [[ ${3} == "PA-AP" ]]; then
    first_sign=""
    second_sign="-"
else
    echo "Invalid phase encoding. Use AP-PA or PA-AP."
    exit
fi

# ----
# Script starts here
# ----

echo "First input b0 file: ${first_input_file}.nii.gz"
echo "Second input b0 file: ${second_input_file}.nii.gz"
echo "Number of volumes in the first file: ${first_size}"
echo "Number of volumes in the second file: ${second_size}"
echo "Phase encoding: ${3}"

# Check if total readout time was passed
if [[ ${4} == "" ]]; then
    echo "Total readout time not passed, using default: ${readout}"
else
    readout=${4}
    echo "Total readout time = ${readout} passed, using it."
fi

# Create empty file
touch ${output_file_name}

# Add number of AP rows corresponding to number of volumes in b0 AP file
for index in $(seq ${first_size});do
    echo "0 ${first_sign}1 0 ${readout}" >> ${output_file_name}
done

# Add number of PA rows corresponding to number of volumes in b0 PA file
for index in $(seq ${second_size});do
    echo "0 ${second_sign}1 0 ${readout}" >> ${output_file_name}
done

echo -e "Created:\n$(cat ${output_file_name})"
