#!/bin/bash

# Function for running matlab from command line without opening MATLAB desktop
# Explanation:
#   https://www.mathworks.com/help/matlab/ref/matlablinux.html
# USAGE:
#   run_matlab "command_1,...,command_X,exit" MATLAB_VERSION
# e.g.
#   run_matlab "addpath('$MATLAB_SCRIPT'),NODDI_analysis('$subdir','$SUB'),exit" R2017b

# Jan Valosek, Rene Labounek, fMRI laboratory, Olomouc, 2018-2021.
# VER=23-04-2021

matlab_dir="/usr/local/MATLAB"
list_of_matlabs=$(ls -d ${matlab_dir}/R* | sed 's/\/usr\/local\/MATLAB\///g')

print_help()
{
        echo -e "Help for function for running matlab from command line without opening MATLAB desktop.\nValosek, Labounek, fMRI laboratory Olomouc, 2018-2021"
        echo -e "\nUSAGE:\n\trun_matlab \"command_1,...,command_X,exit\" MATLAB_VERSION"
	echo -e "EXAMPLE:\n\trun_matlab \"ver,exit\"\nOR"
        echo -e "\trun_matlab \"addpath('\$MATLAB_SCRIPT'),NODDI_analysis('\$subdir','\$SUB'),exit\" R2017b"
        echo -e "\nIf MATLAB_VERSION is not provided, the default matlab under alias matlab is run."
        echo -e "\nAvailable MATLABs on this machine in ${matlab_dir}: \n${list_of_matlabs}"
        exit 0
}

if [[ $1 == "h" ]] || [[ $1 == "-h" ]] || [[ $1 == "--help" ]] || [[ $1 == "" ]] || [[ $# -gt 2 ]]; then
	print_help
fi

command=$1
matlab_ver=$2

if [[ $# -eq 1 ]];then

	if [[ $(which matlab) == "" ]]; then
	    echo "Matlab was not found. Check directory ${matlab_dir} where is MATLAB usually installed."
	    exit 1
	fi

	matlab -nosplash -nodisplay -nodesktop -r  "$command"
else

	if [[ ! -d ${matlab_dir}/${matlab_ver} ]]; then
	        echo -e "ERROR: Matlab version ${matlab_dir}/${matlab_ver} not found.\n"
		print_help
	fi

	${matlab_dir}/${matlab_ver}/bin/matlab -nosplash -nodisplay -nodesktop -r  "$command"

fi
