#!/bin/bash

# Print hostname and IP address to CLI
# Jan Valosek, fMRI laboratory Olomouc, 2021

ifconfig_output=$(sudo ifconfig | grep "inet " | awk '{print $2;}')

echo "Hostname: $(hostname)"
echo "Ethernet IP address: $(echo "$ifconfig_output" | sed -n 1p)"
echo "Wi-Fi IP address: $(echo "$ifconfig_output" | sed -n 2p)"
